import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Practice Next.js",
	description: "Generated by create-next-app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased p-8`}
			>
				<nav className="h-[10vh] flex gap-6 items-center justify-around">
					<Link href={"/"}>Home</Link>
					<Link href={"/about"}>About</Link>
					<Link href={"/exit"}>Exit</Link>
				</nav>
				<div className="flex items-center justify-center w-full h-[75vh]">
					{children}
				</div>
				<footer className="flex items-center justify-center h-[vh15]">
					This is Footer
				</footer>
			</body>
		</html>
	);
}
